import { StyleSheet } from "react-native";

export const s = StyleSheet.create({
  background: {
    flex: 1,
    width: "100%",
    height: "100%",
    justifyContent: "flex-start",
    alignItems: "center",
  },

  overlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
    halfWhiteBackground: {
    width: "100%",
    height: "70%",
    marginTop: "auto",
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 24,
    paddingTop: 18,
    justifyContent: "flex-start",
    zIndex: 2,
  },

  title: {
  position: "absolute",
  left: 20,
  fontSize: 16,
  color: "#5C9F60",
  fontFamily: "Nunito-ExtraBold",
  paddingTop: 35,
  zIndex: 5,
},
blur: {
  position: "absolute",
  top: 0,
  bottom: 0,
  left: 0,
  right: 0,
  borderBottomLeftRadius: 22,
  borderBottomRightRadius: 22,
  zIndex: 1,
},
namesci: {
  position: "absolute",
    bottom: 10,
    fontFamily: "Poppins-Regular",
    left: 10,
    color: "#FFFFFF",
    zIndex: 10,
    fontSize: 11,
},
name: {
    position: "absolute",
    bottom: 25,
    fontFamily: "Poppins-Bold",
    left: 10,
    color: "#FFFFFF",
    zIndex: 10,
    fontSize: 11,
},
second_title: {
  position: "absolute",
  top: 160,
  left: 20,
  fontSize: 16,
  color: "#5C9F60",
  fontFamily: "Nunito-ExtraBold",
  paddingTop: 135,
  zIndex: 5,
},
container2: {
  top: 30,
  width: "105%",
  height: 77,
  backgroundColor: "transparent",
  borderWidth: 1,
  borderColor: "#8F8F8F",
  borderRadius: 25,
  left: -10,
},
textcontainer: {
  position: "absolute",
  top: 11,
    bottom: 35,
    fontFamily: "Nunito-SemiBold",
    left: 15,
    color: "#3C3C3C",
    zIndex: 10,
    fontSize: 15,
    justifyContent: "flex-start",
},
secondtext: {
  position: "absolute",
  top: 15, 
    bottom: 25,
    fontFamily: "Nunito-ExtraBold",
    left: 10,
    color: "#3C3C3C",
    zIndex: 10,
    fontSize: 15,
    justifyContent: "flex-start",
},
desctext: {
  position: "absolute",
    bottom: 15,
    fontFamily: "Poppins-Regular",
    left: 15,
    color: "#3C3C3C",
    zIndex: 10,
    fontSize: 11,
},
desctextname: {
  position: "absolute",
    bottom: 15,
    fontFamily: "Poppins-Bold",
    left: 15,
    color: "#3C3C3C",
    zIndex: 10,
    fontSize: 11,
},
circleButton: {
  width: 40,
  height:40,
  borderRadius: 40,
  backgroundColor: "transparent",
  borderWidth: 8,
  borderColor: "#5C9F60",
  left: 310,
  top: 15,
},


});
